export const ADD_TASK = 'add_task'
export const DELETE_TASK = 'delete_task'
export const COMPLETE_TASK = 'complete_task'
export const CREATE_JOURNAL = 'create_journal'
export const GET_TASKS = 'get_tasks'
export const AUTH_USER = 'auth_user'
